### ISSUE TITLE
Can NOT load dataset...

### ISSUE THREAD

**Issue by zhouchunyi** [Ruiqi-Hu/ARGA#1]
There's an error when I run the model:
<UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 0: illegal multibyte sequence>
This error occurs during loading dataset files in line:
objects.append(pkl.load(open("data/ind.{}.{}".format(dataset, names[i])))) #input_data.py->load_data
I can NOT load these dataset files...
".x",".y"... these files are unreadable, so I can't get the content and format. Could you give some data examples and explain each file?

Sorry...but is there something wrong with my operation?

**Comment by Ruiqi-Hu** [comment]
I guess you are using python 3, however, the code works with python 2.7 just as I write in the requirements.

**Comment by zhouchunyi** [comment]
Thank you for your reply. I used python2.7 at first ,but tensorflow can not be installed successfully for python2. Now ,I run the code in linux with python2.7 successfully.

**Comment by Ruiqi-Hu** [comment]
> Thank you for your reply. I used python2.7 at first ,but tensorflow can not be installed successfully for python2. Now ,I run the code in linux with python2.7 successfully.

Glad to help.
